# melpazoid <https://github.com/riscy/melpazoid> build checks.

# If your package is on GitHub, enable melpazoid's checks by copying this file
# to .github/workflows/melpazoid.yml and modifying RECIPE and EXIST_OK below.

name: melpazoid
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with: { python-version: 3.9 }

    - name: Install
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install emacs && emacs --version
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid

    - name: Check org-zettelkasten
      env:
        LOCAL_REPO: ${{ github.workspace }}
        # RECIPE is your recipe as written for MELPA:
        RECIPE: (org-zettelkasten :repo "ymherklotz/emacs-zettelkasten" :fetcher github :files ("org-zettelkasten.el"))
        # set this to false (or remove it) if the package isn't on MELPA:
        EXIST_OK: true
      run: echo $GITHUB_REF && make -C ~/melpazoid

    - name: Check zettelkasten
      env:
        LOCAL_REPO: ${{ github.workspace }}
        # RECIPE is your recipe as written for MELPA:
        RECIPE: (zettelkasten :repo "ymherklotz/emacs-zettelkasten" :fetcher github :files ("zettelkasten.el"))
        # set this to false (or remove it) if the package isn't on MELPA:
        EXIST_OK: true
      run: echo $GITHUB_REF && make -C ~/melpazoid
